# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7e22bc353afe99e4126cbf9049326118ff38c81acf8a93ac86a04d0e2d6d98740619efc6853fe5c35520b8663303bfd35e94871e693ff9d1a661ead945c08af

test:
  secret_key_base: 5a20d44d78c928d985615016bd57e9c1e8fced8a78d7bb63f5389c2ee78ee71cdcc5b09d9970043af82dde6dea8d5ac7be0937ca5f433419457fa71e2f57c737

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
